# @package _global_

target: DAgger
env:
  name: CoopPuzzle-v0
  parameters:
    grid_size: med
    render_mode: human
model_parameters:
  batch_size: 64
  minibatch_size: 2
  epochs: 10
opt_parameters:
    lr: 1e-4
    eps: 1e-5
transition_file: ["data/trajectories/trajectory2.pkl"]
policy: "Actor"