# @package _global_

env:
  name: CoopPuzzle-v0
  parameters:
    grid_size: med
    render_mode: human
model_parameters:
  verbose: 1
  batch_size: 64
  total_steps: 4000000
  warmup_steps: 4000000
  minibatch_size: 2
  n_epochs: 2
  ent_coef: 0.0
  critic_end_lr: 2.5e-4
  critic_start_lr: 2.5e-4
  actor_end_lr: 0.0
  actor_start_lr: 0.0
  gae_lambda: 0.99
  clip_range: 0.2
  vf_coef: 0.5
  max_grad_norm: 0.2
pretrain_il:
  load: True
  model_path: data/models/imitation/bc_policy4.pkl
phase1:
  load: True
  load_model_path: data/models/ppo_finetuned_policy4_param2.zip
  train: False
  model_parameters:
    total_steps: 4000000
phase2:
  load_model_path: data/models/cooppo_finetune_phase1_2025-03-23_22-28-55.zip
  train: True
  save_model_path: data/models/ppo_finetuned_policy4_phase2_ent_001_final.zip
  model_parameters:
    total_steps: 10000000
    warmup_steps: 3000000
    critic_end_lr: 1e-7
    critic_start_lr: 2.5e-4
    actor_end_lr: 1e-7
    actor_start_lr: 0.0
    ent_coef: 0.001