# @package _global_

env:
  name: CoopPuzzle-v0
  parameters:
    grid_size: med
    render_mode: human
model_parameters:
  save_rl_weights: True
  n_episodes: 1000
  batch_size: 64
  mem_size: 1000000
  n_epochs: 2
  target_update: 2
  lr: 1e-4
  gamma: 0.99
  lambda: 1
transition_file: ["data/trajectories/trajectory2.pkl","data/trajectories/trajectory3.pkl"]